name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: List files in the working directory
      run: ls -la

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: |
        cd build
        cmake ..
        make

    - name: List files in the build directory
      run: ls -la build

    - name: Run C++ program and check output
      id: run_program
      run: ./build/my_program

    - name: Verify function call
      run: |
        if ! grep -q "Hello from my_function!" <(echo "${{ steps.run_program.outputs.stdout }}"); then
          echo "Function my_function was not called"
          exit 1
        fi
        echo "Function my_function was called successfully"
